### ISSUE TITLE
USB NES RetroPort v2 Not Recognized

### ISSUE THREAD

**Issue by jamielovesgames** [kfmike/InputVisualizer#61]
The USB NES RetroPort v2, which is sold by Retro USB, is not being recognized by the InputVisualizer. My PC recognizes it fine (Windows 11) and so does the emulator BizHawk. The NES to USB adapter is found here: https://www.retrousb.com/product_info.php?cPath=21&products_id=158

**Comment by kfmike** [comment]
Support for direct input added today and will be available in a release in the next day or so.
