### ISSUE TITLE
Library(?) issue preventing launch

### ISSUE THREAD

**Issue by Exacerangutan** [kfmike/InputVisualizer#79]
First, let me say I grabbed InputVisualizer (downloaded x64 version on 11/18/24, didn't get around to installing until 1/13) on the recommendation of a streamer (whose name I am of course now blanking on) and I really like it a lot!  I'd been using the GamePad Viewer site before, but I much prefer InputVisualizer, both aesthetically and functionally.

It ran fine when I first installed, fussed around with the settings, and updated my OBS to use it a few days ago--but when I tried to launch it again today, it wouldn't start.  It didn't even throw any user-level errors; I had to go into Event Viewer to see what was going on.  Each time I tried to launch, it threw two errors and an information event:

A .NET Runtime error (ID 1026) "An item with the same key has already been added."
An Application Error (ID 1000) "Faulting module name: KERNELBASE.dll"
And a Windows Error Reporting APPCRASH event

I'm assuming the .NET Runtime error is the actual root issue and the others are downstream fallout, so I'll paste the EventData here, in case that helps to track down the issue.  It _seems_ from the EventData logging as though it's an issue in the InputVisualizer files, but it's entirely possible that's a misread due to something being corrupted on my end.  That doesn't explain to me why it ran fine at first, though, or why I haven't heard of anyone else having the same problem.

Application: InputVisualizer.exe
CoreCLR Version: 7.0.1523.57226
.NET Version: 7.0.15
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: An item with the same key has already been added. Key: 00000003-045e-0000-8e02-000000007200
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at InputVisualizer.InputVisualizer.InitGamepads() in C:\Users\Mike\source\repos\InputVisualizer\InputVisualizer.cs:line 191
   at InputVisualizer.InputVisualizer.Initialize() in C:\Users\Mike\source\repos\InputVisualizer\InputVisualizer.cs:line 68
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Program.<Main>$(String[] args) in C:\Users\Mike\source\repos\InputVisualizer\Program.cs:line 3

Don't hesitate to let me know if there's any other information I can provide to help with this, I'd love to get it up and running again!

**Comment by kfmike** [comment]
Hi Exacerangutan, thank you for the detailed info.
I will take a look at this and get it fixed.

In the meantime, you may be able to recover from this by making a backup of your config.json file in the InputVisualizer directory and then deleting it from there. The config will be re-created when you start the application again and it may resolve the issue temporarily. The only downside is you'd have to re-configure any display settings you made.

This may result in the same error, but it's worth a try until I get a new release pushed out.

Thanks again!

**Comment by kfmike** [comment]
Fixed in version v1.6.3

**Comment by Exacerangutan** [comment]
Awesome!  The fast fix is much appreciated!  I'll keep you informed if any other issues arise.
