### ISSUE TITLE
Mouse Button Binding?

### ISSUE THREAD

**Issue by PrettzL** [kfmike/InputVisualizer#81]
I'm not sure where else to put this but is it possible to bind mouse buttons to be displayed as a button being pressed?

I couldn't find any way to bind Mouse1/2/etc as buttons in the config.

**Comment by kfmike** [comment]
Hi PrettzL, yes that would definitely be possible. I will look into adding this in the near future.

**Comment by kfmike** [comment]
Added in most recent check in. Will be in next release buld
