### ISSUE TITLE
Customization of USB2SNES port

### ISSUE THREAD

**Issue by KrisDavie** [kfmike/InputVisualizer#82]
One of the tools supporting the usb2snes protocol (SNI) l is moving away from using port 8080 as default for the usb2snes websocket. 

Would there be any chance to make the port number customizable? Even if it were just in a config file, it'd be super helpful.

Cheers!

**Comment by kfmike** [comment]
Yes, absolutely. I'll get this in very soon.

**Comment by kfmike** [comment]
Added a general settings menu with the ability to configure USB2SNES server and port in latest version v1.6.4
